spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/auctiondb?useUnicode=true&characterEncoding=UTF-8'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  devtools:
    restart:
      enabled: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
file:
  staticAccessPath: '/upload/**'
  uploadFileFolder: 'D:\\file'